version: '3.7'

services:

  client:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app/
    ports:
      - 8080:8080
    environment:
      - VUE_APP_DEV_SERVER=server
  server:
    image: mediheart-server_server:latest
    ports:
      - 8000:8000